%% Important
% If you use this channel model, please cite our work as

%{

A. Compagnoni, R. Tuninato, C. F. Chiasserini, R. Garello, A. Nordio and E. Viterbo,
"A Highway Vehicular Channel Model for OTFS Performance Evaluation,"
in IEEE Transactions on Communications, vol. 74, pp. 5074-5088, 2026, 
doi: 10.1109/TCOMM.2026.3663522

% BibTex:

@ARTICLE{11390681,
  author={Compagnoni, A. and Tuninato, R. and Chiasserini, C. F. and Garello, R. and Nordio, A. and Viterbo, E.},
  journal={IEEE Transactions on Communications}, 
  title={A Highway Vehicular Channel Model for OTFS Performance Evaluation}, 
  year={2026},
  volume={74},
  number={},
  pages={5074-5088},
  doi={10.1109/TCOMM.2026.3663522}}

%}

%% Generate an istance of a multipath channel using VTDL

% This version generates multipath components, each characterized by a
% complex coefficient and delay. 
% If you want to generate channel coefficients with delays and Doppler
% shifts, refer to Generate_delay_Doppler_channel.m 

function [P,ell,h] = Generate_delay_channel(VTDL,B)

%% Input

% VTDL: this is a structure generated by VTDL_settings 
% (see VTDL_settings for details)

% B: bandwidth (Hz)

%% Output
% P: number of aggregated paths

% h [Px1 double]: complex channel coefficients of different paths (h(1) is
% that of the LoS path, and so on)

% ell [Px1 double]: normalized delays of paths 

%%

time_resolution = 1/B; % (s)

% number of paths
P = VTDL.P; 

% delays
delays = VTDL.delays * 10^(-9); % (s)

% normalized integer delays
ell = round(delays/time_resolution);

% power delay profile
pdp = VTDL.pdp; % (dB)

% linear scale:
pdp_lin = 10.^(pdp/10);

% Complex channel coefficient for each path 
h = sqrt(pdp_lin).*(sqrt(1/2) * (randn(P,1)+1i*randn(P,1))); 

% Aggregate the paths that cannot be resolved by the receiver's resolution
flag = 0;  
while flag == 0
     delays_tmp = ell;

     if length(h) > 1

          unique_delays = unique(ell, 'rows','stable');
          aggregated_delays_taps = [];
          aggregated_chan_coef = [];
          used_indices = [];

          for i = 1:size(unique_delays,1)
               matched_indices = find(ell == unique_delays(i));
               if length(matched_indices) > 1
                      used_indices = [used_indices; matched_indices];
                      new_path_delay_tap = mean(ell(matched_indices));
                      new_chan_coef = sum(h(matched_indices));
                      aggregated_delays_taps = [aggregated_delays_taps; new_path_delay_tap];
                      aggregated_chan_coef = [aggregated_chan_coef; new_chan_coef];
               end
          end

          ell(used_indices) = [];
          h(used_indices)= [];

          ell = [ell;aggregated_delays_taps];
          h = [h;aggregated_chan_coef];

          % sort paths with increasing delay order
          [ell, id_sort] = sort(ell);
          h = h(id_sort);

      end


     if isequal(length(ell),length(delays_tmp))
          flag = 1;
     end
end

P = length(h);

end

